"""empty message

Revision ID: a544ee340b0c
Revises: b6b3ebdb81e0
Create Date: 2024-08-31 03:32:22.128967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a544ee340b0c'
down_revision = 'b6b3ebdb81e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('attendance', sa.String(length=10), nullable=True),
    sa.Column('overall_performance', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'parent_id')
    op.drop_table('progress')
    # ### end Alembic commands ###
