"""empty message

Revision ID: cd8145c34dd3
Revises: 328e2b6b58b0
Create Date: 2024-09-09 23:54:35.117380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8145c34dd3'
down_revision = '328e2b6b58b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('submission_content', sa.Text(), nullable=False),
    sa.Column('submission_file', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('progress', sa.Column('days_present', sa.Integer(), nullable=False))
    op.add_column('progress', sa.Column('days_absent', sa.Integer(), nullable=False))
    op.add_column('progress', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'progress', 'user', ['teacher_id'], ['id'])
    op.drop_column('progress', 'attendance')
    op.add_column('user', sa.Column('days_present', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('days_absent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'days_absent')
    op.drop_column('user', 'days_present')
    op.add_column('progress', sa.Column('attendance', sa.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'progress', type_='foreignkey')
    op.drop_column('progress', 'teacher_id')
    op.drop_column('progress', 'days_absent')
    op.drop_column('progress', 'days_present')
    op.drop_table('assignment_submission')
    # ### end Alembic commands ###
