"""empty message

Revision ID: cd8145c34dd3
Revises: 328e2b6b58b0
Create Date: 2024-09-09 23:54:35.117380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8145c34dd3'
down_revision = '328e2b6b58b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for SQLite batch mode ###
    # Batch mode for progress table
    with op.batch_alter_table('progress') as batch_op:
        batch_op.add_column(sa.Column('days_present', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('days_absent', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_progress_teacher_id', 'user', ['teacher_id'], ['id'])
        batch_op.drop_column('attendance')

    # Batch mode for user table
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(sa.Column('days_present', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('days_absent', sa.Integer(), nullable=True))

    # Create assignment_submission table
    op.create_table(
        'assignment_submission',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('assignment_id', sa.Integer(), nullable=False),
        sa.Column('submission_content', sa.Text(), nullable=False),
        sa.Column('submission_file', sa.String(length=150), nullable=True),
        sa.ForeignKeyConstraint(['student_id'], ['user.id']),
        sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id']),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted for SQLite batch mode ###
    # Drop assignment_submission table
    op.drop_table('assignment_submission')

    # Batch mode for progress table
    with op.batch_alter_table('progress') as batch_op:
        batch_op.add_column(sa.Column('attendance', sa.String(length=10), nullable=True))
        batch_op.drop_constraint('fk_progress_teacher_id', type_='foreignkey')
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('days_absent')
        batch_op.drop_column('days_present')

    # Batch mode for user table
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('days_absent')
        batch_op.drop_column('days_present')
    # ### end Alembic commands ###